[theme]
base = "light"
primaryColor = "#0F2540"
backgroundColor = "#F2EAD5"
secondaryBackgroundColor = "#FBF6E8"
textColor = "#1A1A1A"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
